backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: special_pages
    label: "Special Pages"
    files:
      - name: home
        label: "Home Page"
        file: "content/home.yml"
        fields:
          - name: sections
            label: "Sections"
            widget: list
            fields:
              - { name: title, label: "Title", widget: string }
              - { name: visual, label: "Visual", widget: string }
              - { name: content, label: "Content", widget: string }

  - name: pages
    label: "Pages"
    folder: "content/pages"
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: "Title", widget: string }
      - { name: body, label: "Body", widget: markdown }

  - name: members
    label: "Members"
    folder: "content/members"
    extension: md
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - { name: name, label: "Name", widget: string }
      - { name: body, label: "Biography", widget: markdown }
      - { name: position, label: "Position", widget: string }
      - name: links
        label: "Links"
        widget: list
        fields:
          - { name: type, label: "Type", widget: select, options: ["website"] }
          - { name: url, label: "URL", widget: string, pattern: ["^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?", "Must be a valid URL."] }

  - name: posts
    label: "Blog Posts"
    folder: "content/posts"
    extension: md
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: title, label: "Title", widget: string }
      - { name: date, label: "Date", widget: datetime, time_format: false, date_format: "MM.DD.YYYY" }
      - { name: body, label: "Body", }
