backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: special_pages
    label: "Special Pages"
    files:
      - name: home
        label: "Home Page"
        file: "content/home.yml"
        fields:
          - name: sections
            label: "Sections"
            widget: list
            fields:
              - { name: title, label: "Title", widget: string }
              - { name: visual, label: "Visual", widget: string }
              - { name: content, label: "Content", widget: string }
